[package]
name = "marrow-lsp-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
lsp-types.workspace = true
marrow-syntax.workspace = true
marrow-check.workspace = true
marrow-json.workspace = true
marrow-schema.workspace = true
marrow-project.workspace = true
marrow-store.workspace = true
marrow-run.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
marrow-check = { workspace = true, features = ["test-support"] }
