[package]
name = "marrow-lsp-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
lsp-types.workspace = true
marrow-syntax.workspace = true
marrow-check.workspace = true
marrow-project.workspace = true

[dev-dependencies]
tempfile = "3"
