//! Workspace maintenance tasks.
//!
//! `gen-surface` records the exact set of upstream marrow crates the workspace links —
//! the full transitive closure, so a newly-pulled-in marrow crate (or a dropped one) is a
//! reviewable snapshot diff rather than a silent change. `gen-surface --check` regenerates
//! the snapshot in memory and fails on any difference from the checked-in file, which is
//! how CI turns an upstream API rewrite into a red gate instead of a surprise.

use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

const SNAPSHOT_REL: &str = "pins/consumed-marrow-surface.snapshot";
const PIN_REL: &str = "pins/marrow-rev.toml";

fn main() -> ExitCode {
    let mut args = std::env::args().skip(1);
    match args.next().as_deref() {
        Some("gen-surface") => {
            let check = args.next().as_deref() == Some("--check");
            gen_surface(check)
        }
        other => {
            eprintln!(
                "unknown task {:?}; usage: cargo run -p xtask -- gen-surface [--check]",
                other.unwrap_or("<none>")
            );
            ExitCode::FAILURE
        }
    }
}

fn workspace_root() -> PathBuf {
    // xtask's manifest dir is <root>/xtask, so the workspace root is its parent.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask has a parent directory")
        .to_path_buf()
}

/// Read the pinned marrow revision from `pins/marrow-rev.toml` without a toml dependency:
/// the file is a flat key table, so the `rev = "..."` line is unambiguous.
fn pinned_rev(root: &Path) -> String {
    let text = std::fs::read_to_string(root.join(PIN_REL)).expect("read marrow-rev.toml");
    for line in text.lines() {
        let line = line.trim();
        if let Some(value) = line.strip_prefix("rev") {
            let value = value.trim_start().strip_prefix('=').expect("rev = value");
            return value.trim().trim_matches('"').to_string();
        }
    }
    panic!("no `rev` key in {PIN_REL}");
}

/// The sorted upstream marrow crate closure, rendered as the snapshot body. An upstream
/// crate is a `marrow-*` package whose manifest lives outside this workspace; the
/// workspace's own `marrow-lsp*/marrow-mcp/marrow-dap/marrow-terminal` crates are excluded.
fn consumed_surface(root: &Path) -> String {
    let output = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
        .args(["metadata", "--format-version", "1"])
        .current_dir(root)
        .output()
        .expect("run cargo metadata");
    assert!(
        output.status.success(),
        "cargo metadata failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let metadata: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("parse cargo metadata json");

    let root_str = root.to_string_lossy();
    let mut crates: Vec<(String, String)> = metadata["packages"]
        .as_array()
        .expect("packages array")
        .iter()
        .filter_map(|pkg| {
            let name = pkg["name"].as_str()?;
            let manifest = pkg["manifest_path"].as_str()?;
            let is_upstream_marrow =
                name.starts_with("marrow-") && !manifest.starts_with(&*root_str);
            is_upstream_marrow.then(|| {
                (
                    name.to_string(),
                    pkg["version"].as_str().unwrap_or("").to_string(),
                )
            })
        })
        .collect();
    crates.sort();
    crates.dedup();

    let mut body = String::new();
    for (name, version) in crates {
        body.push_str(&format!("{name} {version}\n"));
    }
    body
}

fn render_snapshot(root: &Path) -> String {
    format!(
        "# Consumed marrow surface — the upstream marrow crate closure this workspace links.\n\
         # Generated by `cargo run -p xtask -- gen-surface`; do not edit by hand.\n\
         # A diff here means an upstream crate was added or dropped: review it, do not paper over it.\n\
         # Pinned marrow rev: {rev}\n\
         {body}",
        rev = pinned_rev(root),
        body = consumed_surface(root),
    )
}

fn gen_surface(check: bool) -> ExitCode {
    let root = workspace_root();
    let generated = render_snapshot(&root);
    let path = root.join(SNAPSHOT_REL);

    if check {
        let existing = std::fs::read_to_string(&path).unwrap_or_default();
        if existing == generated {
            println!("consumed-marrow-surface snapshot is up to date");
            ExitCode::SUCCESS
        } else {
            eprintln!(
                "consumed-marrow-surface snapshot is stale.\n\
                 Regenerate with `cargo run -p xtask -- gen-surface` and review the diff.\n\
                 --- checked in ---\n{existing}\n--- generated ---\n{generated}"
            );
            ExitCode::FAILURE
        }
    } else {
        std::fs::write(&path, &generated).expect("write snapshot");
        println!("wrote {SNAPSHOT_REL}");
        ExitCode::SUCCESS
    }
}
